# Generated by Django 2.2.2 on 2019-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=21),
        ),
    ]
